version: '3'
services:
  backend:
    image: my-server-image
    container_name: my-backend-server
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/codinnator/data/uploads/
      - ./application.properties:/app/config/application.properties