version: '3'
services:
  backend:
    build: .
    image: my-server-image:latest
    container_name: my-backend-server
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /home/ubuntu/codinnator/uploads:/codinnator/data/uploads/
      - /home/ubuntu/config:/config
