import type { AutoCompleteItem } from "@/types/room/editor/types";

// Java 키워드
const JAVA_KEYWORDS: AutoCompleteItem[] = [
  { label: "public", type: "keyword" },
  { label: "private", type: "keyword" },
  { label: "protected", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "interface", type: "keyword" },
  { label: "extends", type: "keyword" },
  { label: "implements", type: "keyword" },
  { label: "abstract", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "throws", type: "keyword" },
  { label: "new", type: "keyword" },
  { label: "this", type: "keyword" },
  { label: "super", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "final", type: "keyword" },
  { label: "void", type: "keyword" },
  { label: "null", type: "keyword" },
  { label: "true", type: "keyword" },
  { label: "false", type: "keyword" },
  { label: "import", type: "keyword" },
  { label: "package", type: "keyword" },
  { label: "instanceof", type: "keyword" },
  { label: "int", type: "keyword" },
  { label: "long", type: "keyword" },
  { label: "short", type: "keyword" },
  { label: "byte", type: "keyword" },
  { label: "float", type: "keyword" },
  { label: "double", type: "keyword" },
  { label: "boolean", type: "keyword" },
  { label: "char", type: "keyword" },
];

// Java 내장 클래스
const JAVA_CLASSES: AutoCompleteItem[] = [
  { label: "String", type: "class" },
  { label: "Integer", type: "class" },
  { label: "Long", type: "class" },
  { label: "Double", type: "class" },
  { label: "Boolean", type: "class" },
  { label: "Character", type: "class" },
  { label: "Object", type: "class" },
  { label: "ArrayList", type: "class" },
  { label: "LinkedList", type: "class" },
  { label: "HashMap", type: "class" },
  { label: "HashSet", type: "class" },
  { label: "TreeMap", type: "class" },
  { label: "TreeSet", type: "class" },
  { label: "List", type: "class" },
  { label: "Map", type: "class" },
  { label: "Set", type: "class" },
  { label: "Scanner", type: "class" },
  { label: "BufferedReader", type: "class" },
  { label: "BufferedWriter", type: "class" },
  { label: "FileReader", type: "class" },
  { label: "FileWriter", type: "class" },
  { label: "Arrays", type: "class" },
  { label: "Collections", type: "class" },
  { label: "Math", type: "class" },
  { label: "System", type: "class" },
  { label: "Exception", type: "class" },
  { label: "RuntimeException", type: "class" },
  { label: "NullPointerException", type: "class" },
  { label: "IOException", type: "class" },
];

// 메서드와 스니펫
const JAVA_METHODS: AutoCompleteItem[] = [
  { label: "println", type: "method", insertText: "System.out.println();" },
  { label: "print", type: "method", insertText: "System.out.print();" },
  { label: "printf", type: "method", insertText: "System.out.printf();" },
  { label: "main", type: "snippet", insertText: "public static void main(String[] args) {\n    \n}" },
  { label: "psvm", type: "snippet", insertText: "public static void main(String[] args) {\n    \n}" },
  { label: "toString", type: "method" },
  { label: "equals", type: "method" },
  { label: "hashCode", type: "method" },
  { label: "length", type: "method" },
  { label: "size", type: "method" },
  { label: "get", type: "method" },
  { label: "set", type: "method" },
  { label: "add", type: "method" },
  { label: "remove", type: "method" },
  { label: "contains", type: "method" },
  { label: "isEmpty", type: "method" },
];

// 전체 자동완성 항목
export const ALL_JAVA_ITEMS: AutoCompleteItem[] = [
  ...JAVA_KEYWORDS,
  ...JAVA_CLASSES,
  ...JAVA_METHODS,
];
